global:
  scrape_interval: 5s

scrape_configs:
  #Services / Infrastructure
  - job_name: "analytics-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["analytics-service:8085"]

  - job_name: "auth-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: "gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gateway:8080"]

  - job_name: "service-discovery"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["service-discovery:8761"]

  #mongo db
