server:
  port: ${ANALYTICS_SERVICE_INSTANCE_PORT:8085}

spring:
  application:
    name: ${ANALYTICS_SERVICE_INSTANCE_HOSTNAME:analytics-service}
  data:
    mongodb:
      uri: ${ANALYTICS_MONGODB_URI:mongodb://localhost:27017/analyticsservicedb}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://service-discovery:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: ${ANALYTICS_SERVICE_INSTANCE_HOSTNAME:analytics-service}
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}

management:
  server:
    port: ${ANALYTICS_SERVICE_INSTANCE_PORT:8085}
    servlet:
      context-path: /
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name:analytics-service}

logging:
  level:
    com.smartgym: DEBUG
    org.springframework: INFO
