server:
  port: ${SERVICE_DISCOVERY_INSTANCE_PORT:8761}

spring:
  application:
    name: ${SERVICE_DISCOVERY_INSTANCE_HOSTNAME:service-discovery}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name:service-discovery}
  server:
    port: ${SERVICE_DISCOVERY_INSTANCE_PORT:8761}
